import { PROJECT_CRITERIA_BY_ID, type CriterionAssessment, type CriterionPillarId, type SDStandardProject } from "../../../../../packages/standard-core/src/project";
import criteriaEs from "../../../../../packages/standard-core/src/i18n/criteria.es.json";
import { getCriterionDocMeta } from "@/lib/criteria-docs";

const pillars: Array<{ id: CriterionPillarId; en: string; es: string }> = [
  { id: "environment", en: "Environment", es: "Medio ambiente" }, { id: "society", en: "Society", es: "Sociedad" },
  { id: "culture", en: "Culture", es: "Cultura" }, { id: "finance", en: "Finance", es: "Finanzas" },
];
const esLabels = criteriaEs as Record<string, { label?: string }>;

type Coverage = "planned" | "in-progress" | "implemented" | "evidence" | "not-addressed" | "not-applicable";
function coverage(item: CriterionAssessment): Coverage {
  if (item.status === "not-applicable" || item.relevance === "not-applicable") return "not-applicable";
  if (item.response === "verified") return "evidence";
  if (item.status === "completed") return "implemented";
  if (item.status === "in-progress") return "in-progress";
  if (item.status === "planned") return "planned";
  return "not-addressed";
}
const coverageText: Record<Coverage, { en: string; es: string }> = {
  planned: { en: "Planned", es: "Planificado" }, "in-progress": { en: "In progress", es: "En curso" }, implemented: { en: "Implemented", es: "Implementado" },
  evidence: { en: "Supported by evidence", es: "Con evidencia" }, "not-addressed": { en: "Not addressed", es: "No abordado" },
  "not-applicable": { en: "Not applicable", es: "No aplica" },
};

export function PassportDocument({ project, preview = false }: { project: SDStandardProject; preview?: boolean }) {
  const spanish = project.passport.locale === "es"; const lang = spanish ? "es" : "en"; const p = project.passport;
  const t = (en: string, es: string) => spanish ? es : en;
  const reviewed = project.criteriaAssessments.filter(item => item.status !== "not-reviewed").length;
  const withActions = project.criteriaAssessments.filter(item => item.strategies.some(strategy => ["selected", "in-progress", "completed"].includes(strategy.status))).length;
  const componentById = new Map(project.components.map(component => [component.id, component]));
  const assessmentsFor = (id: string) => project.criteriaAssessments.filter(item => item.scope.level === "component" && item.scope.componentIds.includes(id));
  return <article className={`passport-document${preview ? " passport-preview" : ""}`} lang={lang}>
    <header className="passport-hero"><div><p className="public-eyebrow">{t("Project Passport", "Pasaporte del proyecto")}{preview ? ` · ${t("Preview", "Vista previa")}` : ""}</p><h1>{project.project.title}</h1><p className="passport-purpose">{p.purpose || project.project.description}</p><dl className="passport-meta">{p.location && <div><dt>{t("Location", "Lugar")}</dt><dd>{p.location}</dd></div>}{p.event && <div><dt>{t("Event", "Evento")}</dt><dd>{p.event}</dd></div>}<div><dt>{t("Last updated", "Última actualización")}</dt><dd>{p.lastUpdated || t("Not set", "Sin fecha")}</dd></div></dl></div>{p.heroImage.src && <figure><img src={p.heroImage.src} alt={p.heroImage.alt} /><figcaption>{p.heroImage.caption}{p.heroImage.credit && <> · {t("Credit", "Crédito")}: {p.heroImage.credit}</>}</figcaption></figure>}</header>

    <nav className="passport-jump" aria-label={t("Passport sections", "Secciones del pasaporte")}><a href="#components">{t("Components", "Componentes")}</a><a href="#coverage">{t("Criteria", "Criterios")}</a><a href="#snapshot">{t("Snapshot", "Resumen")}</a><a href="#evidence">{t("Evidence", "Evidencia")}</a></nav>

    <section className="public-section" id="components"><p className="public-eyebrow">01</p><h2>{t("Project components", "Componentes del proyecto")}</h2><div className="passport-components">{project.components.map(component => <article id={`component-${component.id}`} key={component.id}>{component.image?.src && <figure><img src={component.image.src} alt={component.image.alt} /><figcaption>{component.image.caption}{component.image.credit && <> · {component.image.credit}</>}</figcaption></figure>}<p className="passport-type">{component.type}</p><h3>{component.name}</h3><p>{component.description || t("Description needed.", "Falta una descripción.")}</p><h4>{t("Key choices", "Decisiones clave")}</h4>{assessmentsFor(component.id).flatMap(item => item.strategies.filter(strategy => strategy.status !== "suggested").map(strategy => <div className="passport-choice" key={`${item.criterionId}-${strategy.id}`}><span>{strategy.status === "rejected" ? t("Not chosen", "Descartada") : coverageText[coverage(item)][lang]}</span><p>{strategy.title}{strategy.description ? ` — ${strategy.description}` : ""}</p></div>)).length ? <div className="passport-choices">{assessmentsFor(component.id).flatMap(item => item.strategies.filter(strategy => strategy.status !== "suggested").map(strategy => <div className="passport-choice" key={`${item.criterionId}-${strategy.id}`}><span>{strategy.status === "rejected" ? t("Not chosen", "Descartada") : coverageText[coverage(item)][lang]}</span><p>{strategy.title}{strategy.description ? ` — ${strategy.description}` : ""}</p></div>))}</div> : <p className="passport-empty">{t("No public decisions documented yet.", "Aún no hay decisiones públicas documentadas.")}</p>}<div className="passport-tags">{assessmentsFor(component.id).map(item => { const def = PROJECT_CRITERIA_BY_ID.get(item.criterionId); return def && <a href={`#criterion-${item.criterionId}`} key={item.criterionId}>{def.displayId} · {spanish ? esLabels[item.criterionId]?.label ?? def.label : def.label}</a>; })}</div></article>)}</div></section>

    <section className="public-section" id="coverage"><p className="public-eyebrow">02</p><h2>{t("Component × criterion", "Componentes × criterios")}</h2><p>{t("Each criterion appears once. Follow its component links to the decisions above.", "Cada criterio aparece una sola vez. Sus enlaces llevan a las decisiones de los componentes.")}</p><div className="passport-pillars">{pillars.map(pillar => { const items = project.criteriaAssessments.filter(item => PROJECT_CRITERIA_BY_ID.get(item.criterionId)?.pillarId === pillar.id); if (!items.length) return null; return <section className={`passport-pillar is-${pillar.id}`} key={pillar.id}><h3>{pillar[lang]}</h3>{items.map(item => { const def = PROJECT_CRITERIA_BY_ID.get(item.criterionId)!; const doc = getCriterionDocMeta(item.criterionId); const targets = item.scope.level === "component" ? item.scope.componentIds.map(id => componentById.get(id)).filter(Boolean) : []; return <article id={`criterion-${item.criterionId}`} key={item.criterionId}><div><span className={`passport-status is-${coverage(item)}`}>{coverageText[coverage(item)][lang]}</span><h4>{doc ? <a href={doc.url} target="_blank" rel="noreferrer">{def.displayId} · {spanish ? esLabels[item.criterionId]?.label ?? def.label : def.label}</a> : `${def.displayId} · ${def.label}`}</h4></div><div className="passport-tags">{item.scope.level === "project" && <span>{t("Whole project", "Proyecto completo")}</span>}{targets.map(component => component && <a href={`#component-${component.id}`} key={component.id}>{component.name}</a>)}</div></article>; })}</section>; })}</div></section>

    <section className="public-section" id="snapshot"><p className="public-eyebrow">03</p><h2>{t("Assessment snapshot", "Resumen de evaluación")}</h2><p className="passport-caveat">{t("This is a record of criteria coverage and supporting evidence—not a score, impact percentage, certification, or grade.", "Este es un registro de cobertura de criterios y evidencia de respaldo; no es una puntuación, porcentaje de impacto, certificación ni calificación.")}</p><div className="passport-totals"><div><strong>{reviewed}</strong><span>{t("criteria reviewed", "criterios revisados")}</span></div><div><strong>{withActions}</strong><span>{t("with documented actions", "con acciones documentadas")}</span></div></div><div className="passport-snapshot">{pillars.map(pillar => { const items = project.criteriaAssessments.filter(item => PROJECT_CRITERIA_BY_ID.get(item.criterionId)?.pillarId === pillar.id); return <article key={pillar.id}><h3>{pillar[lang]}</h3><strong>{items.length}</strong><span>{t("selected criteria", "criterios seleccionados")}</span><ul>{(["planned", "in-progress", "implemented", "evidence", "not-addressed", "not-applicable"] as Coverage[]).map(state => <li key={state}><span>{coverageText[state][lang]}</span><b>{items.filter(item => coverage(item) === state).length}</b></li>)}</ul></article>; })}</div></section>

    <section className="public-section" id="evidence"><p className="public-eyebrow">04</p><h2>{t("Outcomes and evidence", "Resultados y evidencia")}</h2>{p.outcomes.length ? <div className="passport-outcomes">{p.outcomes.map(outcome => <article key={outcome.id}><span className="passport-status">{outcome.kind}</span><h3>{outcome.label}</h3><p className="passport-value">{outcome.value} {outcome.unit}</p><dl><div><dt>{t("Source", "Fuente")}</dt><dd>{outcome.source}</dd></div><div><dt>{t("Date", "Fecha")}</dt><dd>{outcome.date}</dd></div></dl>{outcome.evidenceNote && <p>{outcome.evidenceNote}</p>}</article>)}</div> : <div className="passport-empty"><h3>{t("No outcomes measured yet", "Aún no hay resultados medidos")}</h3><p>{t("Measurements and observations will appear here with units, source, date, and whether they are measured, estimated, or intended.", "Las mediciones y observaciones aparecerán aquí con unidad, fuente, fecha y una etiqueta de medido, estimado o previsto.")}</p></div>}</section>

    <section className="public-section"><p className="public-eyebrow">05</p><h2>{t("What we would improve", "Qué mejoraríamos")}</h2><p>{p.improvements || t("Open questions and trade-offs have not been documented yet.", "Aún no se han documentado preguntas abiertas ni disyuntivas.")}</p></section>
    <section className="public-section"><h2>{t("Collaborators and credits", "Colaboradores y créditos")}</h2>{p.collaborators.length ? <div className="passport-people">{p.collaborators.map(person => <article key={person.id}><h3>{person.name}</h3><p>{person.role}</p>{person.credit && <small>{person.credit}</small>}</article>)}</div> : <p className="passport-empty">{t("Collaborator names and roles await review.", "Los nombres y roles de colaboradores están pendientes de revisión.")}</p>}</section>
  </article>;
}
