import { Link } from "wouter";
import { PageIntro, PageMeta } from "@/public-site/PageIntro";
import { team, foundingContributors, roadmap, audiences } from "@/public-site/about-content";

export default function About() {
  return <main className="public-page">
    <PageMeta title="About" description="The SD Standard is a practical framework for responsible decisions before, during and after a communication design project." />
    <PageIntro title="Better questions. More responsible design." eyebrow="About the SD Standard" description="Our mission is to ensure communication designers and other creatives have the tools and resources to do their best work for the world." />
    <section className="public-section" id="what-is-the-sd-standard"><h2>What is the SD Standard?</h2><p>The SD Standard is a practical framework for helping visual communication designers make more responsible decisions before, during, and after a project.</p><p>It is organized around four pillars: environment, society, culture, and finance, and applies to areas such as graphic design, editorial design, exhibit design, signage, packaging, web design, film, video, animation, interactive design, and motion graphics.</p><div className="public-actions"><Link className="public-link" href="/explore/pillars">Understand the four pillars →</Link><Link className="public-link" href="/explore">Explore the Standard →</Link></div></section>
    <section className="public-section" id="why-it-exists"><h2>Why it exists</h2><p>Many sustainability tools focus on architecture, product design, or corporate ESG reporting, while visual communication design often lacks practical criteria for everyday project decisions, often leaving communication design as a last item in the decision-making process of organizations.</p><p>Designers influence material choices, messaging, accessibility, production methods, cultural representation, budgets, and stakeholder participation, impacting what gets produced, for whom, with whom, and by what means.</p><p>Sustainability in design should go beyond the material aspects of design. A strong design standard should also consider equity, labour, culture, affordability, transparency, and long-term value.</p><p><strong>Our goal is to help designers ask better questions early enough to influence outcomes.</strong></p></section>
    <section className="public-section" id="who-developed-it"><h2>Who developed it</h2><p>The Sustainable Design Standard’s vision began in 2012 at ico-D, the International Council of Design’s Sustainability Committee. Led by chair David Berman, the vision was to transform claims of sustainability into credible and measurable metrics.</p><p>In 2016, ico-D granted ownership of the work to three members who had taken on the majority of the work and specialized in sustainable communications: Alex Quinto, Valerie Elliott, and Tuuli Sauren.</p><div className="public-people">{team.map(person => <article key={person.name}><h3>{person.name}</h3><p className="public-person-role">{person.role}</p><details><summary>Read biography</summary><p>{person.bio}</p></details></article>)}</div><details className="public-founders"><summary>Founding members and contributors</summary><p>{foundingContributors}</p></details></section>
    <section className="public-section" id="who-is-it-for"><h2>Who it is for</h2><div className="public-types">{audiences.map(item => <article key={item.title}><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></section>
    <section className="public-section" id="roadmap"><h2>Where the initiative is heading</h2><p>The existing roadmap sets out the initiative’s direction.</p><ol className="public-roadmap">{roadmap.map(item => <li key={item.stage}><span>{item.stage}</span><div><h3>{item.title}</h3><p>{item.description}</p></div></li>)}</ol></section>
    <section className="public-section"><h2>Participate in what comes next.</h2><div className="public-actions"><Link className="public-button" href="/about/get-involved">Get involved →</Link><Link className="public-link" href="/about/updates">Read updates →</Link></div></section>
  </main>;
}
