import { Plus, Trash2 } from "lucide-react";
import type { ProjectCollaborator, ProjectOutcome } from "../../../../../packages/standard-core/src/project";
import { PassportDocument } from "@/public-site/PassportDocument";
import { useWorkspace } from "./WorkspaceProvider";
import { dangerButton, fieldClass, primaryButton, secondaryButton } from "./ui";

const id = (prefix: string) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;

export function PassportView({ onGo }: { onGo: (path: string) => void }) {
  const workspace = useWorkspace(); const project = workspace.project; if (!project) return null; const passport = project.passport;
  const updateCollaborator = (personId: string, patch: Partial<ProjectCollaborator>) => workspace.updateProjectPassport({ collaborators: passport.collaborators.map(person => person.id === personId ? { ...person, ...patch } : person) });
  const updateOutcome = (outcomeId: string, patch: Partial<ProjectOutcome>) => workspace.updateProjectPassport({ outcomes: passport.outcomes.map(outcome => outcome.id === outcomeId ? { ...outcome, ...patch } : outcome) });
  const gaps = [!project.project.description && ["Project description", "/workspace"], !passport.purpose && ["Passport purpose", "/workspace/passport"], project.components.length === 0 && ["Project components", "/workspace/components"], project.criteriaAssessments.length === 0 && ["Selected criteria", "/workspace/criteria"], !passport.lastUpdated && ["Last updated date", "/workspace/passport"]].filter(Boolean) as string[][];
  return <div className="grid gap-9"><header><p className="text-xs font-extrabold uppercase tracking-widest text-[#28775e]">Project Passport</p><h2 className="mt-2 text-3xl font-extrabold">Edit and preview the public record</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#5f5a50]">This preview is assembled only from the open browser project. It is not public and is never uploaded automatically.</p></header>
    {gaps.length > 0 && <section className="rounded-md border border-[#b07918] bg-[#fff8e5] p-5" aria-labelledby="passport-gaps"><h3 className="font-extrabold" id="passport-gaps">Complete before publishing</h3><ul className="mt-3 grid gap-2 text-sm">{gaps.map(([label, path]) => <li className="flex flex-wrap items-center justify-between gap-3" key={label}><span>{label}</span><button className={secondaryButton} type="button" onClick={() => onGo(path)}>Edit field</button></li>)}</ul></section>}
    <section className="rounded-md border border-[#d9d4c8] bg-[#fffdf8] p-5 sm:p-6"><h3 className="text-xl font-extrabold">Editorial details</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-extrabold md:col-span-2">Purpose<textarea className={`${fieldClass} min-h-24`} value={passport.purpose} onChange={event => workspace.updateProjectPassport({ purpose: event.target.value })} /></label><label className="text-sm font-extrabold">Location<input className={fieldClass} value={passport.location} onChange={event => workspace.updateProjectPassport({ location: event.target.value })} /></label><label className="text-sm font-extrabold">Event or context<input className={fieldClass} value={passport.event} onChange={event => workspace.updateProjectPassport({ event: event.target.value })} /></label><label className="text-sm font-extrabold">Language<select className={fieldClass} value={passport.locale} onChange={event => workspace.updateProjectPassport({ locale: event.target.value })}><option value="en">English</option><option value="es">Español</option></select></label><label className="text-sm font-extrabold">Last updated<input className={fieldClass} type="date" value={passport.lastUpdated} onChange={event => workspace.updateProjectPassport({ lastUpdated: event.target.value })} /></label><label className="text-sm font-extrabold">Hero image URL<input className={fieldClass} value={passport.heroImage.src} onChange={event => workspace.updateProjectPassport({ heroImage: { ...passport.heroImage, src: event.target.value } })} /></label><label className="text-sm font-extrabold">Hero image alt text<input className={fieldClass} value={passport.heroImage.alt} onChange={event => workspace.updateProjectPassport({ heroImage: { ...passport.heroImage, alt: event.target.value } })} /></label><label className="text-sm font-extrabold">Hero image caption<input className={fieldClass} value={passport.heroImage.caption} onChange={event => workspace.updateProjectPassport({ heroImage: { ...passport.heroImage, caption: event.target.value } })} /></label><label className="text-sm font-extrabold">Hero image credit<input className={fieldClass} value={passport.heroImage.credit} onChange={event => workspace.updateProjectPassport({ heroImage: { ...passport.heroImage, credit: event.target.value } })} /></label><label className="text-sm font-extrabold md:col-span-2">What we would improve<textarea className={`${fieldClass} min-h-24`} value={passport.improvements} onChange={event => workspace.updateProjectPassport({ improvements: event.target.value })} /></label></div></section>
    <section className="rounded-md border border-[#d9d4c8] bg-[#fffdf8] p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-extrabold">Collaborators and credits</h3><p className="mt-1 text-sm text-[#5f5a50]">Publish names only with appropriate permission and credit.</p></div><button className={primaryButton} type="button" onClick={() => workspace.updateProjectPassport({ collaborators: [...passport.collaborators, { id: id("collaborator"), name: "", role: "", credit: "" }] })}><Plus className="h-4 w-4" />Add collaborator</button></div><div className="mt-5 grid gap-4">{passport.collaborators.map(person => <div className="grid gap-3 rounded border border-[#d9d4c8] p-4 md:grid-cols-3" key={person.id}><label className="text-sm font-extrabold">Name<input className={fieldClass} value={person.name} onChange={event => updateCollaborator(person.id, { name: event.target.value })} /></label><label className="text-sm font-extrabold">Role<input className={fieldClass} value={person.role} onChange={event => updateCollaborator(person.id, { role: event.target.value })} /></label><label className="text-sm font-extrabold">Credit line<input className={fieldClass} value={person.credit} onChange={event => updateCollaborator(person.id, { credit: event.target.value })} /></label><button className={dangerButton} type="button" onClick={() => workspace.updateProjectPassport({ collaborators: passport.collaborators.filter(item => item.id !== person.id) })}><Trash2 className="h-4 w-4" />Remove</button></div>)}</div></section>
    <section className="rounded-md border border-[#d9d4c8] bg-[#fffdf8] p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-extrabold">Outcomes and evidence</h3><p className="mt-1 text-sm text-[#5f5a50]">Record a quantity or observation with units, source, date, status, and evidence note.</p></div><button className={primaryButton} type="button" onClick={() => workspace.updateProjectPassport({ outcomes: [...passport.outcomes, { id: id("outcome"), label: "", value: "", unit: "", kind: "intended", source: "", date: "", evidenceNote: "" }] })}><Plus className="h-4 w-4" />Add outcome</button></div><div className="mt-5 grid gap-4">{passport.outcomes.map(outcome => <div className="grid gap-3 rounded border border-[#d9d4c8] p-4 md:grid-cols-3" key={outcome.id}><label className="text-sm font-extrabold md:col-span-2">Outcome<input className={fieldClass} value={outcome.label} onChange={event => updateOutcome(outcome.id, { label: event.target.value })} /></label><label className="text-sm font-extrabold">Status<select className={fieldClass} value={outcome.kind} onChange={event => updateOutcome(outcome.id, { kind: event.target.value as ProjectOutcome["kind"] })}><option value="measured">Measured</option><option value="estimated">Estimated</option><option value="intended">Intended</option></select></label><label className="text-sm font-extrabold">Value<input className={fieldClass} value={outcome.value} onChange={event => updateOutcome(outcome.id, { value: event.target.value })} /></label><label className="text-sm font-extrabold">Unit<input className={fieldClass} value={outcome.unit} onChange={event => updateOutcome(outcome.id, { unit: event.target.value })} /></label><label className="text-sm font-extrabold">Date<input className={fieldClass} type="date" value={outcome.date} onChange={event => updateOutcome(outcome.id, { date: event.target.value })} /></label><label className="text-sm font-extrabold md:col-span-3">Source<input className={fieldClass} value={outcome.source} onChange={event => updateOutcome(outcome.id, { source: event.target.value })} /></label><label className="text-sm font-extrabold md:col-span-3">Evidence note<textarea className={`${fieldClass} min-h-20`} value={outcome.evidenceNote} onChange={event => updateOutcome(outcome.id, { evidenceNote: event.target.value })} /></label><button className={dangerButton} type="button" onClick={() => workspace.updateProjectPassport({ outcomes: passport.outcomes.filter(item => item.id !== outcome.id) })}><Trash2 className="h-4 w-4" />Remove</button></div>)}</div></section>
    <section className="rounded-md border-2 border-[#28775e] bg-[#e5efe9] p-5"><h3 className="text-xl font-extrabold">Exactly what a publication may expose</h3><p className="mt-2 text-sm leading-6">Title, public description and project types; passport purpose, location, event, date, public images and credits, collaborators, outcomes, evidence notes, and improvements; component names, types, descriptions and public images; criterion IDs, scope, coverage states, and strategy titles/descriptions.</p><p className="mt-3 text-sm font-extrabold text-[#365146]">Excluded by default: project notes, component notes, strategy notes, local file paths, budgets, contact details, browser storage metadata, and unpublished evidence.</p><p className="mt-3 text-sm">Publishing is a manual editorial step: review the downloaded JSON, copy only the public fields into a repository passport record, and deploy the site. Nothing on this screen uploads data.</p></section>
    <section aria-labelledby="passport-preview-heading"><h3 className="text-2xl font-extrabold" id="passport-preview-heading">Live preview</h3><div className="mt-5 overflow-hidden rounded-md border border-[#d9d4c8] bg-[#f7f5ef] p-4 sm:p-7"><PassportDocument project={project} preview /></div></section>
  </div>;
}
